/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesTeethWhiteningRouteImport } from './routes/services.teeth-whitening'
import { Route as ServicesPeriodonticsRouteImport } from './routes/services.periodontics'
import { Route as ServicesOralSurgeryRouteImport } from './routes/services.oral-surgery'
import { Route as ServicesHollywoodSmileRouteImport } from './routes/services.hollywood-smile'
import { Route as ServicesDentalImplantsRouteImport } from './routes/services.dental-implants'
import { Route as ServicesBracesRouteImport } from './routes/services.braces'
import { Route as ServicesAestheticDentistryRouteImport } from './routes/services.aesthetic-dentistry'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTeethWhiteningRoute = ServicesTeethWhiteningRouteImport.update({
  id: '/teeth-whitening',
  path: '/teeth-whitening',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesPeriodonticsRoute = ServicesPeriodonticsRouteImport.update({
  id: '/periodontics',
  path: '/periodontics',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesOralSurgeryRoute = ServicesOralSurgeryRouteImport.update({
  id: '/oral-surgery',
  path: '/oral-surgery',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesHollywoodSmileRoute = ServicesHollywoodSmileRouteImport.update({
  id: '/hollywood-smile',
  path: '/hollywood-smile',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDentalImplantsRoute = ServicesDentalImplantsRouteImport.update({
  id: '/dental-implants',
  path: '/dental-implants',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesBracesRoute = ServicesBracesRouteImport.update({
  id: '/braces',
  path: '/braces',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAestheticDentistryRoute =
  ServicesAestheticDentistryRouteImport.update({
    id: '/aesthetic-dentistry',
    path: '/aesthetic-dentistry',
    getParentRoute: () => ServicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/aesthetic-dentistry': typeof ServicesAestheticDentistryRoute
  '/services/braces': typeof ServicesBracesRoute
  '/services/dental-implants': typeof ServicesDentalImplantsRoute
  '/services/hollywood-smile': typeof ServicesHollywoodSmileRoute
  '/services/oral-surgery': typeof ServicesOralSurgeryRoute
  '/services/periodontics': typeof ServicesPeriodonticsRoute
  '/services/teeth-whitening': typeof ServicesTeethWhiteningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/aesthetic-dentistry': typeof ServicesAestheticDentistryRoute
  '/services/braces': typeof ServicesBracesRoute
  '/services/dental-implants': typeof ServicesDentalImplantsRoute
  '/services/hollywood-smile': typeof ServicesHollywoodSmileRoute
  '/services/oral-surgery': typeof ServicesOralSurgeryRoute
  '/services/periodontics': typeof ServicesPeriodonticsRoute
  '/services/teeth-whitening': typeof ServicesTeethWhiteningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/aesthetic-dentistry': typeof ServicesAestheticDentistryRoute
  '/services/braces': typeof ServicesBracesRoute
  '/services/dental-implants': typeof ServicesDentalImplantsRoute
  '/services/hollywood-smile': typeof ServicesHollywoodSmileRoute
  '/services/oral-surgery': typeof ServicesOralSurgeryRoute
  '/services/periodontics': typeof ServicesPeriodonticsRoute
  '/services/teeth-whitening': typeof ServicesTeethWhiteningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/gallery'
    | '/services'
    | '/sitemap.xml'
    | '/services/aesthetic-dentistry'
    | '/services/braces'
    | '/services/dental-implants'
    | '/services/hollywood-smile'
    | '/services/oral-surgery'
    | '/services/periodontics'
    | '/services/teeth-whitening'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/gallery'
    | '/services'
    | '/sitemap.xml'
    | '/services/aesthetic-dentistry'
    | '/services/braces'
    | '/services/dental-implants'
    | '/services/hollywood-smile'
    | '/services/oral-surgery'
    | '/services/periodontics'
    | '/services/teeth-whitening'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/gallery'
    | '/services'
    | '/sitemap.xml'
    | '/services/aesthetic-dentistry'
    | '/services/braces'
    | '/services/dental-implants'
    | '/services/hollywood-smile'
    | '/services/oral-surgery'
    | '/services/periodontics'
    | '/services/teeth-whitening'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GalleryRoute: typeof GalleryRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/teeth-whitening': {
      id: '/services/teeth-whitening'
      path: '/teeth-whitening'
      fullPath: '/services/teeth-whitening'
      preLoaderRoute: typeof ServicesTeethWhiteningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/periodontics': {
      id: '/services/periodontics'
      path: '/periodontics'
      fullPath: '/services/periodontics'
      preLoaderRoute: typeof ServicesPeriodonticsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/oral-surgery': {
      id: '/services/oral-surgery'
      path: '/oral-surgery'
      fullPath: '/services/oral-surgery'
      preLoaderRoute: typeof ServicesOralSurgeryRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/hollywood-smile': {
      id: '/services/hollywood-smile'
      path: '/hollywood-smile'
      fullPath: '/services/hollywood-smile'
      preLoaderRoute: typeof ServicesHollywoodSmileRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/dental-implants': {
      id: '/services/dental-implants'
      path: '/dental-implants'
      fullPath: '/services/dental-implants'
      preLoaderRoute: typeof ServicesDentalImplantsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/braces': {
      id: '/services/braces'
      path: '/braces'
      fullPath: '/services/braces'
      preLoaderRoute: typeof ServicesBracesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/aesthetic-dentistry': {
      id: '/services/aesthetic-dentistry'
      path: '/aesthetic-dentistry'
      fullPath: '/services/aesthetic-dentistry'
      preLoaderRoute: typeof ServicesAestheticDentistryRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesAestheticDentistryRoute: typeof ServicesAestheticDentistryRoute
  ServicesBracesRoute: typeof ServicesBracesRoute
  ServicesDentalImplantsRoute: typeof ServicesDentalImplantsRoute
  ServicesHollywoodSmileRoute: typeof ServicesHollywoodSmileRoute
  ServicesOralSurgeryRoute: typeof ServicesOralSurgeryRoute
  ServicesPeriodonticsRoute: typeof ServicesPeriodonticsRoute
  ServicesTeethWhiteningRoute: typeof ServicesTeethWhiteningRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAestheticDentistryRoute: ServicesAestheticDentistryRoute,
  ServicesBracesRoute: ServicesBracesRoute,
  ServicesDentalImplantsRoute: ServicesDentalImplantsRoute,
  ServicesHollywoodSmileRoute: ServicesHollywoodSmileRoute,
  ServicesOralSurgeryRoute: ServicesOralSurgeryRoute,
  ServicesPeriodonticsRoute: ServicesPeriodonticsRoute,
  ServicesTeethWhiteningRoute: ServicesTeethWhiteningRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GalleryRoute: GalleryRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
